### ISSUE TITLE
pkgs= references an invalid dependency: guestfs-tools on fc34

### ISSUE THREAD

**Issue by atomicturtle** [rocky-linux/OpenQA-Fedora-Installation#10]
**Describe Issue**

On FC34 (and likely EL8) dnf/yum will return an invalid package due to a typo in the naming for the libguestfs-tools dependency in pkgs

**Planned Action**

Update pkgs field to reference the correct dependency

**Comment by StackKorora** [comment]
Merged. Thanks!
